### ISSUE TITLE
Soporte a Url de votación configurable/personalizable

### ISSUE THREAD

**Issue by Jesusjbs** [egc-veleta-g2/decide#41]
**Descripción del problema**

El problema se da cuando se crea una votación donde la URL personalizada contiene el símbolo `/`.
En concreto, el error es que al intentar acceder a la votación desde la cabina usando dicha URL personalizada el signo `/` se interpreta como una ruta en lugar de como una cadena de texto, dando lugar a un error 404 con el mensaje Page not found,  the current path, booth/prueba/url, didn't match any of these. 

**Replicación del problema**

1. Creo una votación con la URL personalizada `prueba/url`
2.  Asigno una pregunta y una autoridad ya creada a la votación anterior. Además incluyo al usuario para votar en el censo.
2. Inicio la votación.
3. Accedo a la URL `http://127.0.0.1:8000/booth/prueba/url` para poder votar, obteniendo el error mencionado al comienzo.

**Capturas de la aplicación**

![image](https://user-images.githubusercontent.com/62173360/147413314-911c902b-69bc-4077-a365-37afbc7ecbcf.png)
Captura de la página de error al intentar acceder a la votación desde la cabina.

**Necesidades del subsistema cabina**

Se espera/necesita volver a hacer accesible votación desde la cabina mediante una validación de las URLs personalizadas que se pueden introducir.

**Propuesta de cambio**

Se propone a la hora de crear un modelo votación, añadir una validación en el campo URL para que un usuario no pueda crear una votación con una URL que contenga el signo `/`.

**Comment by julibamon** [comment]
Arreglada la incidencia
