### ISSUE TITLE
Soporte a creación de preguntas (2)

### ISSUE THREAD

**Issue by zorgary** [egc-veleta-g2/decide#59]
**Descripción del problema**

Se ha implementado una página intermedia para poder seleccionar el tipo de pregunta que se desea crear. No obstante, solo es accesible desde la página de inicio de administrador. Cuando se intenta crear una pregunta desde el formulario de una votación, nos redirige a una pregunta normal, sin posibilidad de elegir por ejemplo la pregunta dicotómica.

**Replicación del problema**

1. Accedo al menú de administrador de la página.
2. Le doy a crear una votación.
3. Doy click al botón "+" que aparece para añadir una pregunta.
4. Me aparece el formulario de una pregunta normal en lugar de la página intermedia.

**Capturas de la aplicación**

![Captura](https://user-images.githubusercontent.com/72384337/147923081-2dcfc047-10a0-43c2-8d3b-9e9689ca7069.png)

**Necesidades del subsistema Voting**

Se espera que se cambie la redirección para que en lugar de acceder a la pregunta por defecto, se lleve al usuario a la página intermedia de elección de preguntas. 

**Propuesta de cambio**

Se propone modificar el enlace de redirección del botón "+" de esta página, para que apunte a la página intermedia de elección como ocurre en la página de inicio de administrador.

**Comment by manmogvil** [comment]
Para su realización sería necesario realizar demasiados cambios y por lo tanto, no se va a realizar
