### ISSUE TITLE
Soporte a creación de preguntas

### ISSUE THREAD

**Issue by Jesusjbs** [egc-veleta-g2/decide#61]
**Descripción del problema**

Cuando se pretende crear una pregunta a través del botón `ADD QUESTION` el cual se encuentra en la parte superior derecha de la página del listado de preguntas, debería de enviar a la página intermedia para elegir el tipo de pregunta a crear. Sin embargo, envía al formulario de crear una pregunta por defecto.

**Replicación del problema**

Enumerar los pasos a seguir para replicar el problema. Ejemplo:
1. Entro en la página de administrador del sistema.
2. Accedo al listado de questions.
3. Pulso en el enlace `ADD QUESTION` que se encuentra arriba a la derecha y ocurre el error.

**Capturas de la aplicación (opcional, si se cree necesario)**

![image](https://user-images.githubusercontent.com/62173360/147923117-0800184a-048d-4a3d-a6a2-11990b4208cf.png)
Captura del listado de questions donde aparece arriba a la derecha el botón que tiene el error

**Necesidades del subsistema voting**

Se espera que el botón envíe a la página intermedia para seleccionar qué votación se desea crear en lugar de al formulario.

**Propuesta de cambio**

Se propone modificar el `href` del botón para que envíe a la página intermedia.

**Comment by manmogvil** [comment]
Para su realización sería necesario realizar demasiados cambios y por lo tanto, no se va a realizar
